language: python

matrix:
  include:
    - python: 3.5
      env:
        - COVERAGE=false

    - python: 3.6
      env:
        - COVERAGE=false

    - python: 3.7
      # dist: xenial
      # sudo: true
      env:
        - COVERAGE=true
    
    - python: 3.8
      # dist: xenial
      # sudo: true
      env:
        - COVERAGE=true


install:
  - pip install requests pillow pytest pytest-mpl
  - pip install .

script:
  - python check_mpl_template.py --mpl --verbose

after_success:
  - if [ ${COVERAGE} = true ]; then
      pip install coverage codecov;
      coverage run --source mpl_template check_mpl_template.py;
      coverage report -m;
      codecov;
    fi
