language: python

matrix:
  include:
    - python: 3.6
      env:
        - COVERAGE=false
    - python: 3.7
      env:
        - COVERAGE=false
    - python: 3.8
      env:
        - COVERAGE=true


install:
  - pip install requests pillow pytest pytest-mpl
  - pip install .

script:
  - pytest --mpl --verbose

after_success:
  - if [ ${COVERAGE} = true ]; then
      pip install coverage codecov;
      coverage run --source mpl_template -m pytest;
      coverage report -m;
      codecov;
    fi
