name: Lint & Test

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: Install Linters
        run: |
          pip install -U pip
          pip install black isort
      - name: Run Linters
        run: |
          black . --check --diff
          isort . --check --diff

  test:
    env:
      USING_COVERAGE: "3.9"
    env:
      USING_COVERAGE: "3.9"
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install project
        run: |
          pip install -U pip
          pip install requests pillow pytest pytest-mpl
          pip install .
      - name: Run tests
        run: pytest --mpl --verbose
      - name: Run coverage
        if: contains(env.USING_COVERAGE, matrix.python-version)
        run: |
          pip install coverage
          coverage run --branch -m pytest --mpl --verbose
          coverage report -mi
          coverage xml
      - name: Upload coverage to Codecov
        if: contains(env.USING_COVERAGE, matrix.python-version)
        uses: codecov/codecov-action@v2
        with:
          fail_ci_if_error: true
